### ISSUE TITLE
Graphical mode not rendering

### ISSUE THREAD

**Issue by jimdandrews** [forcedotcom/try-acb-feedback#49]
<!— This repo is for feedback on Anypoint Code Builder during open Beta, please limit your issues to those associated with Anypoint Code Builder. Please let us know if you encounter any issues both creating or launching the web IDEs along with issues implementing your use cases.

This is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels. -->

**Describe the bug**
Using Desktop ACB, I was trying to open a flow from an existing project which had been built using Studio.  This project had some bigger, more significant flows to work with.  I was able to import the project just fine, but opening any of the project flow xml's causes the xml to open on the right (as expected) and the graphical mode to hang with the message "Preparing flow canvas". 
I thought it might be the complexity of the flow, or dependencies it couldn't reach. So, then, as an experiment, i uploaded a very simple project with a single flow that I had built in Desktop ACB to the Web IDE.  And the same thing happened.  the graphical view hangs up "preparing flow canvas".
So, then i took the more complex Studio flow, and in my open simple project in Desktop ACB , I opened an existing flow file and pasted in flows from the complex flow.  and it worked.  So it doesn't seem like the graphical viewer is finding the flows too complex to render. 

**To Reproduce**

1. create a basic API project in ACB Desktop
2. use a simple flow like an HTTP listener that logs a message and sets the payload as a hard coded string value
3. upload the project folder to the ACB Web IDE
4. open the folder
5. open the flow file.
6. flow canvas hangs

Likewise,
1. create a project in Studio,
2. create a flow
3. import the project into ACB desktop
4. open the flow file
5. flow canvas hangs.

**Expected behavior**
I expect the projects to behave the same regarless of the origin of the project.

**Impact**
Select from 
* Malfunctioning
* Poor Usability
* Fit & Finish UI

**Frequency**
Select from 
* Always

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.  They really help!
<img width="1703" alt="image" src="https://github.com/forcedotcom/try-acb-feedback/assets/7758054/1ce2f078-f5c0-432e-ae4a-cc33aa627d84">
<img width="1563" alt="image" src="https://github.com/forcedotcom/try-acb-feedback/assets/7758054/395f17ae-a276-46e3-b9b9-432d3148c323">

**Please complete the following information:**

* [Anypoint Code Builder web IDE URL](https://plains-wm1crfzp.iad.003.anypoint.code-builder.platform.salesforce.com)
* chrome
* 24.4.6

VC version 1.81.1
VC extension pack plugin v1.0.2

**Additional context**

**Comment by sravannerella** [comment]
Hi, I'm trying the latest version of ACB Desktop and running into this issue. This seems to be happening when I open the Mule code built with the Anypoint Studio code in ACB. It gets stuck in Rendering and even after 15-20 mins, it seems to be stuck there.

**Comment by simoneegeib** [comment]
Hi @sravannerella , this is likely because there are some dependencies missing in your project. Please open the output and check the errors in the log. 
In Jim's case, he had to log into Anypoint platform, so that his dependencies from Exchange were loaded into the project

**Comment by sravannerella** [comment]
@simoneegeib, thanks for getting back to me. I attempted to clean the project and install the dependencies while logged into the Anypoint platform. Even after a refresh, I'm still running into this issue. Please find the below screenshot for reference. Please suggest. Thank you 😊 

<img width="1330" alt="image" src="https://github.com/forcedotcom/try-acb-feedback/assets/12230220/28c71818-3dca-453a-ba1f-061647841c28">

**Comment by simoneegeib** [comment]
I don't see any errors. Please go to output and select "Mule DX Server" and let me know if you see any exceptions there

**Comment by sravannerella** [comment]
Hello @simoneegeib, Please find the logs from the Mule DX Server. Btw, I performed mvn clean and opened the project multiple times, yet I run into the same error.

```
java.lang.IllegalStateException: Cannot explore URL: file:/Users/sravannerella/.m2/repository/org/apache/cxf/cxf-core/3.5.5/cxf-core-3.5.5.jar
	at org.mule.runtime.module.artifact.internal.util.FileJarExplorer.explore(FileJarExplorer.java:127)
	at org.mule.runtime.module.deployment.impl.internal.maven.AbstractMavenClassLoaderModelLoader.discoverLocalPackages(AbstractMavenClassLoaderModelLoader.java:466)
	at org.mule.runtime.module.deployment.impl.internal.maven.AbstractMavenClassLoaderModelLoader.createLightPackageClassLoaderModel(AbstractMavenClassLoaderModelLoader.java:434)
```

![image](https://github.com/forcedotcom/try-acb-feedback/assets/12230220/42b503f1-2763-4a66-9d7a-146f75c56bfa)
